/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMXRT1021xxxxx
package_id: MIMXRT1021DAG5A
mcu_data: ksdk2_0
processor_version: 9.0.1
board: MIMXRT1020-EVK
pin_labels:
- {pin_num: '49', pin_signal: ONOFF, label: ONOFF}
- {pin_num: '53', pin_signal: PMIC_ON_REQ, label: PMIC_ON_REQ}
- {pin_num: '51', pin_signal: TEST_MODE, label: GND}
- {pin_num: '63', pin_signal: USB_OTG1_DP, label: OTG1_DP}
- {pin_num: '62', pin_signal: USB_OTG1_DN, label: OTG1_DN}
- {pin_num: '6', pin_signal: VSS0, label: GND}
- {pin_num: '40', pin_signal: VSS1, label: GND}
- {pin_num: '60', pin_signal: VSS2, label: GND}
- {pin_num: '70', pin_signal: VSS3, label: GND}
- {pin_num: '85', pin_signal: VSS4, label: GND}
- {pin_num: '103', pin_signal: VSS5, label: GND}
- {pin_num: '113', pin_signal: VSS6, label: GND}
- {pin_num: '135', pin_signal: VSS7, label: GND}
- {pin_num: '14', pin_signal: GPIO_EMC_04, label: 'SEMC_D4/U14[8]', identifier: SEMC_D4}
- {pin_num: '5', pin_signal: VDD_SOC_IN0, label: VDD_SOC_IN}
- {pin_num: '31', pin_signal: VDD_SOC_IN1, label: VDD_SOC_IN}
- {pin_num: '39', pin_signal: VDD_SOC_IN2, label: VDD_SOC_IN}
- {pin_num: '86', pin_signal: VDD_SOC_IN3, label: VDD_SOC_IN}
- {pin_num: '102', pin_signal: VDD_SOC_IN4, label: VDD_SOC_IN}
- {pin_num: '114', pin_signal: VDD_SOC_IN5, label: VDD_SOC_IN}
- {pin_num: '134', pin_signal: VDD_SOC_IN6, label: VDD_SOC_IN}
- {pin_num: '65', pin_signal: VDD_HIGH_CAP, label: VDDA_2P5_CAP}
- {pin_num: '56', pin_signal: VDD_SNVS_CAP, label: GND}
- {pin_num: '69', pin_signal: VDD_HIGH_IN, label: VDD_HIGH_IN_MCU}
- {pin_num: '55', pin_signal: VDD_SNVS_IN, label: VDD_SNVS_IN}
- {pin_num: '72', pin_signal: NVCC_PLL, label: VDDA_1P1_CAP}
- {pin_num: '11', pin_signal: NVCC_GPIO0, label: NVCC_GPIO_3V3}
- {pin_num: '20', pin_signal: NVCC_GPIO1, label: NVCC_GPIO_3V3}
- {pin_num: '29', pin_signal: NVCC_GPIO2, label: NVCC_GPIO_3V3}
- {pin_num: '144', pin_signal: NVCC_GPIO6, label: NVCC_GPIO_3V3}
- {pin_num: '59', pin_signal: USB_OTG1_VBUS, label: 5V_USB_OTG}
- {pin_num: '64', pin_signal: NGND_KEL0, label: GND}
- {pin_num: '73', pin_signal: VDDA_ADC_3P3, label: VDDA_ADC_3P3_MCU}
- {pin_num: '61', pin_signal: VDD_USB_CAP, label: VDD_USB_3V}
- {pin_num: '38', pin_signal: DCDC_IN_Q, label: MCU_DCDC_IN_3V3}
- {pin_num: '52', pin_signal: WAKEUP, label: USER_BUTTON}
- {pin_num: '34', pin_signal: DCDC_IN, label: MCU_DCDC_IN_3V3}
- {pin_num: '36', pin_signal: DCDC_LP, label: DCDC_OUT}
- {pin_num: '35', pin_signal: DCDC_GND, label: GND}
- {pin_num: '37', pin_signal: DCDC_PSWITCH, label: MCU_DCDC_IN_3V3}
- {pin_num: '54', pin_signal: PMIC_STBY_REQ, label: SD_PWREN}
- {pin_num: '44', pin_signal: NVCC_SD0, label: NVCC_SD}
- {pin_num: '18', pin_signal: GPIO_EMC_00, label: 'SEMC_D0/U14[2]', identifier: SEMC_D0}
- {pin_num: '17', pin_signal: GPIO_EMC_01, label: 'SEMC_D1/U14[4]', identifier: SEMC_D1}
- {pin_num: '16', pin_signal: GPIO_EMC_02, label: 'SEMC_D2/U14[5]', identifier: SEMC_D2}
- {pin_num: '15', pin_signal: GPIO_EMC_03, label: 'SEMC_D3/U14[7]', identifier: SEMC_D3}
- {pin_num: '13', pin_signal: GPIO_EMC_05, label: 'SEMC_D5/U14[10]', identifier: SEMC_D5}
- {pin_num: '12', pin_signal: GPIO_EMC_06, label: 'SEMC_D6/U14[11]', identifier: SEMC_D6}
- {pin_num: '10', pin_signal: GPIO_EMC_07, label: 'SEMC_D7/U14[13]', identifier: SEMC_D7}
- {pin_num: '9', pin_signal: GPIO_EMC_08, label: 'SEMC_DM0/U14[15]', identifier: SEMC_DM0}
- {pin_num: '8', pin_signal: GPIO_EMC_09, label: 'SEMC_WE/U14[16]', identifier: SEMC_WE}
- {pin_num: '7', pin_signal: GPIO_EMC_10, label: 'SEMC_CAS/U14[17]', identifier: SEMC_CAS}
- {pin_num: '4', pin_signal: GPIO_EMC_11, label: 'SEMC_RAS/U14[18]', identifier: SEMC_RAS}
- {pin_num: '3', pin_signal: GPIO_EMC_12, label: 'SEMC_CS0/U14[19]', identifier: SEMC_CS0}
- {pin_num: '2', pin_signal: GPIO_EMC_13, label: 'SEMC_BA0/U14[20]', identifier: SEMC_BA0}
- {pin_num: '1', pin_signal: GPIO_EMC_14, label: 'SEMC_BA1/U14[21]', identifier: SEMC_BA1}
- {pin_num: '143', pin_signal: GPIO_EMC_15, label: 'SEMC_A10/U14[22]', identifier: SEMC_A10}
- {pin_num: '142', pin_signal: GPIO_EMC_16, label: 'SEMC_A0/U14[23]/BOOT_MODE[0]', identifier: SEMC_A0}
- {pin_num: '141', pin_signal: GPIO_EMC_17, label: 'SEMC_A1/U14[24]/BOOT_MODE[1]', identifier: SEMC_A1}
- {pin_num: '140', pin_signal: GPIO_EMC_18, label: 'SEMC_A2/U14[25]/BT_CFG[0]', identifier: SEMC_A2}
- {pin_num: '139', pin_signal: GPIO_EMC_19, label: 'SEMC_A3/U14[26]/BT_CFG[1]', identifier: SEMC_A3}
- {pin_num: '138', pin_signal: GPIO_EMC_20, label: 'SEMC_A4/U14[29]/BT_CFG[2]', identifier: SEMC_A4}
- {pin_num: '137', pin_signal: GPIO_EMC_21, label: 'SEMC_A5/U14[30]/BT_CFG[3]', identifier: SEMC_A5}
- {pin_num: '136', pin_signal: GPIO_EMC_22, label: 'SEMC_A6/U14[31]/BT_CFG[4]', identifier: SEMC_A6}
- {pin_num: '133', pin_signal: GPIO_EMC_23, label: 'SEMC_A7/U14[32]/BT_CFG[5]', identifier: SEMC_A7}
- {pin_num: '132', pin_signal: GPIO_EMC_24, label: 'SEMC_A8/U14[33]/BT_CFG[6]', identifier: SEMC_A8}
- {pin_num: '131', pin_signal: GPIO_EMC_25, label: 'SEMC_A9/U14[34]/BT_CFG[7]', identifier: SEMC_A9}
- {pin_num: '130', pin_signal: GPIO_EMC_26, label: 'SEMC_A11/U14[35]/BT_CFG[8]', identifier: SEMC_A11}
- {pin_num: '129', pin_signal: GPIO_EMC_27, label: 'SEMC_A12/U14[36]/BT_CFG[9]', identifier: SEMC_A12}
- {pin_num: '128', pin_signal: GPIO_EMC_28, label: SEMC_DQS, identifier: SEMC_DQS}
- {pin_num: '127', pin_signal: GPIO_EMC_29, label: 'SEMC_CKE/U14[37]', identifier: SEMC_CKE}
- {pin_num: '126', pin_signal: GPIO_EMC_30, label: 'SEMC_CLK/U14[38]', identifier: SEMC_CLK}
- {pin_num: '125', pin_signal: GPIO_EMC_31, label: 'SEMC_DM1/U14[39]', identifier: SEMC_DM1}
- {pin_num: '124', pin_signal: GPIO_EMC_32, label: 'SEMC_D8/U14[42]', identifier: SEMC_D8}
- {pin_num: '123', pin_signal: GPIO_EMC_33, label: 'SEMC_D9/U14[44]', identifier: SEMC_D9}
- {pin_num: '122', pin_signal: GPIO_EMC_34, label: 'SEMC_D10/U14[45]', identifier: SEMC_D10}
- {pin_num: '121', pin_signal: GPIO_EMC_35, label: 'SEMC_D11/U14[47]', identifier: SEMC_D11}
- {pin_num: '120', pin_signal: GPIO_EMC_36, label: 'SEMC_D12/U14[48]', identifier: SEMC_D12}
- {pin_num: '119', pin_signal: GPIO_EMC_37, label: 'SEMC_D13/U14[50]', identifier: SEMC_D13}
- {pin_num: '118', pin_signal: GPIO_EMC_38, label: 'SEMC_D14/U14[51]', identifier: SEMC_D14}
- {pin_num: '117', pin_signal: GPIO_EMC_39, label: 'SEMC_D15/U14[53]', identifier: SEMC_D15}
- {pin_num: '116', pin_signal: GPIO_EMC_40, label: 'ENET_MDIO/U11[11]', identifier: ENET_MDIO}
- {pin_num: '115', pin_signal: GPIO_EMC_41, label: 'ENET_MDC/U11[12]', identifier: ENET_MDC}
- {pin_num: '112', pin_signal: NVCC_GPIO5, label: NVCC_GPIO_3V3}
- {pin_num: '104', pin_signal: NVCC_GPIO4, label: NVCC_GPIO_3V3}
- {pin_num: '77', pin_signal: NVCC_GPIO3, label: NVCC_GPIO_3V3}
- {pin_num: '111', pin_signal: GPIO_AD_B0_00, label: 'JTAG_TMS/J16[7]/SWD_DIO'}
- {pin_num: '110', pin_signal: GPIO_AD_B0_01, label: 'JTAG_TCK/J16[9]/SWD_CLK'}
- {pin_num: '109', pin_signal: GPIO_AD_B0_02, label: GND}
- {pin_num: '108', pin_signal: GPIO_AD_B0_03, label: 'JTAG_TDI/J16[5]/WDOG_B'}
- {pin_num: '107', pin_signal: GPIO_AD_B0_04, label: 'JTAG_TDO/J16[13]/ENET_RST/U11[32]', identifier: ENET_RST}
- {pin_num: '106', pin_signal: GPIO_AD_B0_05, label: D4, identifier: D4;GPIO1_05}
- {pin_num: '105', pin_signal: GPIO_AD_B0_06, label: D5, identifier: D5;GPIO1_06}
- {pin_num: '101', pin_signal: GPIO_AD_B0_07, label: D3, identifier: D3;GPIO1_07}
- {pin_num: '100', pin_signal: GPIO_AD_B0_08, label: 'ENET_TX_CLK/U11[9]', identifier: ENET_TX_CLK}
- {pin_num: '99', pin_signal: GPIO_AD_B0_09, label: D2, identifier: D2}
- {pin_num: '98', pin_signal: GPIO_AD_B0_10, label: CLK, identifier: CLK}
- {pin_num: '97', pin_signal: GPIO_AD_B0_11, label: PCS0, identifier: PCS0}
- {pin_num: '96', pin_signal: GPIO_AD_B0_12, label: MOSI, identifier: MOSI}
- {pin_num: '95', pin_signal: GPIO_AD_B0_13, label: MISO, identifier: MISO}
- {pin_num: '94', pin_signal: GPIO_AD_B0_14, label: D6, identifier: D6;GPIO1_14}
- {pin_num: '93', pin_signal: GPIO_AD_B0_15, label: D9, identifier: D9;GPIO1_15}
- {pin_num: '92', pin_signal: GPIO_AD_B1_00, label: SAI1_MCLK}
- {pin_num: '91', pin_signal: GPIO_AD_B1_01, label: SAI1_TX_BCLK}
- {pin_num: '90', pin_signal: GPIO_AD_B1_02, label: D15, identifier: D15;GPIO1_18}
- {pin_num: '89', pin_signal: GPIO_AD_B1_03, label: D14, identifier: D14;GPIO1_19}
- {pin_num: '88', pin_signal: GPIO_AD_B1_04, label: AUD_INT}
- {pin_num: '87', pin_signal: GPIO_AD_B1_05, label: SAI1_RXD}
- {pin_num: '84', pin_signal: GPIO_AD_B1_06, label: D7, identifier: D7;GPIO1_22}
- {pin_num: '83', pin_signal: GPIO_AD_B1_07, label: D8, identifier: D8;GPIO1_23}
- {pin_num: '80', pin_signal: GPIO_AD_B1_10, label: A0, identifier: A0;GPIO1_26}
- {pin_num: '79', pin_signal: GPIO_AD_B1_11, label: A1, identifier: A1;GPIO1_27}
- {pin_num: '78', pin_signal: GPIO_AD_B1_12, label: A2, identifier: A2;GPIO1_28}
- {pin_num: '76', pin_signal: GPIO_AD_B1_13, label: A3, identifier: A3;GPIO1_29}
- {pin_num: '75', pin_signal: GPIO_AD_B1_14, label: A5, identifier: A5;GPIO1_30}
- {pin_num: '74', pin_signal: GPIO_AD_B1_15, label: A4, identifier: A4;GPIO1_31}
- {pin_num: '48', pin_signal: GPIO_SD_B0_00, label: 'SD1_D2/J15[1]', identifier: SD1_D2}
- {pin_num: '47', pin_signal: GPIO_SD_B0_01, label: 'SD1_D3/J15[2]', identifier: SD1_D3}
- {pin_num: '46', pin_signal: GPIO_SD_B0_02, label: 'SD1_CMD/J15[3]', identifier: SD1_CMD}
- {pin_num: '45', pin_signal: GPIO_SD_B0_03, label: 'SD1_CLK/J15[5]', identifier: SD1_CLK}
- {pin_num: '43', pin_signal: GPIO_SD_B0_04, label: 'SD1_D0/J15[7]', identifier: SD1_D0}
- {pin_num: '42', pin_signal: GPIO_SD_B0_05, label: 'SD1_D1/J15[8]', identifier: SD1_D1}
- {pin_num: '41', pin_signal: GPIO_SD_B0_06, label: 'SD_CD_SW/J15[9]', identifier: SD_CD_SW}
- {pin_num: '33', pin_signal: GPIO_SD_B1_00, label: 'CAN1_TX/U9[1]', identifier: CAN1_TX}
- {pin_num: '32', pin_signal: GPIO_SD_B1_01, label: 'CAN1_RX/U9[4]', identifier: CAN1_RX}
- {pin_num: '30', pin_signal: GPIO_SD_B1_02, label: I2C4_SCL}
- {pin_num: '25', pin_signal: GPIO_SD_B1_06, label: 'FlexSPI_D3_A/U13[7]', identifier: FlexSPI_D3_A}
- {pin_num: '26', pin_signal: GPIO_SD_B1_05, label: INT2_COMBO}
- {pin_num: '27', pin_signal: GPIO_SD_B1_04, label: INT1_COMBO}
- {pin_num: '28', pin_signal: GPIO_SD_B1_03, label: D14_IO3, identifier: D14_IO3}
- {pin_num: '24', pin_signal: GPIO_SD_B1_07, label: 'FlexSPI_CLK/U13[6]', identifier: FlexSPI_CLK}
- {pin_num: '23', pin_signal: GPIO_SD_B1_08, label: 'FlexSPI_D0_A/U13[5]', identifier: FlexSPI_D0_A}
- {pin_num: '22', pin_signal: GPIO_SD_B1_09, label: 'FlexSPI_D2_A/U13[3]', identifier: FlexSPI_D2_A}
- {pin_num: '21', pin_signal: GPIO_SD_B1_10, label: 'FlexSPI_D1_A/U13[2]', identifier: FlexSPI_D1_A}
- {pin_num: '19', pin_signal: GPIO_SD_B1_11, label: 'FlexSPI_SS0/U13[1]', identifier: FlexSPI_SS0}
- {pin_num: '50', pin_signal: POR_B, label: 'POR_B/J16[5]/RST_TGTMCU_B/J20[3]'}
- {pin_num: '81', pin_signal: GPIO_AD_B1_09, label: UART_RX, identifier: UART_RX}
- {pin_num: '82', pin_signal: GPIO_AD_B1_08, label: UART_TX, identifier: UART_TX}
- {pin_num: '67', pin_signal: XTALI, label: XTALI}
- {pin_num: '68', pin_signal: XTALO, label: XTALO}
- {pin_num: '57', pin_signal: RTC_XTALI, label: RTC_XTALI}
- {pin_num: '58', pin_signal: RTC_XTALO, label: RTC_XTALO}
power_domains: {NVCC_GPIO: '3.3'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    ARDUINO();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
ARDUINO:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '101', peripheral: GPIO1, signal: 'gpio_io, 07', pin_signal: GPIO_AD_B0_07, identifier: D3, direction: INPUT}
  - {pin_num: '106', peripheral: GPIO1, signal: 'gpio_io, 05', pin_signal: GPIO_AD_B0_05, identifier: D4, direction: OUTPUT, drive_strength: R0_6, pull_keeper_select: Keeper,
    pull_up_down_config: Pull_Down_100K_Ohm}
  - {pin_num: '99', peripheral: GPIO1, signal: 'gpio_io, 09', pin_signal: GPIO_AD_B0_09, direction: OUTPUT}
  - {pin_num: '105', peripheral: GPIO1, signal: 'gpio_io, 06', pin_signal: GPIO_AD_B0_06, identifier: D5, direction: INPUT}
  - {pin_num: '94', peripheral: GPIO1, signal: 'gpio_io, 14', pin_signal: GPIO_AD_B0_14, identifier: D6, direction: OUTPUT}
  - {pin_num: '84', peripheral: GPIO1, signal: 'gpio_io, 22', pin_signal: GPIO_AD_B1_06, identifier: D7, direction: INPUT}
  - {pin_num: '98', peripheral: LPSPI1, signal: SCK, pin_signal: GPIO_AD_B0_10}
  - {pin_num: '96', peripheral: LPSPI1, signal: SDO, pin_signal: GPIO_AD_B0_12}
  - {pin_num: '97', peripheral: LPSPI1, signal: PCS0, pin_signal: GPIO_AD_B0_11}
  - {pin_num: '95', peripheral: LPSPI1, signal: SDI, pin_signal: GPIO_AD_B0_13}
  - {pin_num: '81', peripheral: LPUART2, signal: RX, pin_signal: GPIO_AD_B1_09}
  - {pin_num: '82', peripheral: LPUART2, signal: TX, pin_signal: GPIO_AD_B1_08}
  - {pin_num: '80', peripheral: GPIO1, signal: 'gpio_io, 26', pin_signal: GPIO_AD_B1_10, identifier: A0, direction: OUTPUT}
  - {pin_num: '79', peripheral: GPIO1, signal: 'gpio_io, 27', pin_signal: GPIO_AD_B1_11, identifier: A1, direction: OUTPUT}
  - {pin_num: '78', peripheral: GPIO1, signal: 'gpio_io, 28', pin_signal: GPIO_AD_B1_12, identifier: A2, direction: OUTPUT}
  - {pin_num: '76', peripheral: GPIO1, signal: 'gpio_io, 29', pin_signal: GPIO_AD_B1_13, identifier: A3, direction: OUTPUT}
  - {pin_num: '74', peripheral: GPIO1, signal: 'gpio_io, 31', pin_signal: GPIO_AD_B1_15, identifier: A4, direction: OUTPUT}
  - {pin_num: '75', peripheral: GPIO1, signal: 'gpio_io, 30', pin_signal: GPIO_AD_B1_14, identifier: A5, direction: OUTPUT}
  - {pin_num: '83', peripheral: GPIO1, signal: 'gpio_io, 23', pin_signal: GPIO_AD_B1_07, identifier: D8, direction: OUTPUT}
  - {pin_num: '93', peripheral: GPIO1, signal: 'gpio_io, 15', pin_signal: GPIO_AD_B0_15, identifier: D9, direction: INPUT}
  - {pin_num: '89', peripheral: GPIO1, signal: 'gpio_io, 19', pin_signal: GPIO_AD_B1_03, identifier: D14, direction: OUTPUT}
  - {pin_num: '90', peripheral: GPIO1, signal: 'gpio_io, 18', pin_signal: GPIO_AD_B1_02, identifier: D15, direction: OUTPUT}
  - {pin_num: '28', peripheral: GPIO3, signal: 'gpio_io, 23', pin_signal: GPIO_SD_B1_03, direction: OUTPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : ARDUINO
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void ARDUINO(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of D4 on GPIO_AD_B0_05 (pin 106) */
  gpio_pin_config_t D4_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_05 (pin 106) */
  GPIO_PinInit(GPIO1, 5U, &D4_config);

  /* GPIO configuration of D5 on GPIO_AD_B0_06 (pin 105) */
  gpio_pin_config_t D5_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_06 (pin 105) */
  GPIO_PinInit(GPIO1, 6U, &D5_config);

  /* GPIO configuration of D3 on GPIO_AD_B0_07 (pin 101) */
  gpio_pin_config_t D3_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_07 (pin 101) */
  GPIO_PinInit(GPIO1, 7U, &D3_config);

  /* GPIO configuration of D2 on GPIO_AD_B0_09 (pin 99) */
  gpio_pin_config_t D2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_09 (pin 99) */
  GPIO_PinInit(GPIO1, 9U, &D2_config);

  /* GPIO configuration of D6 on GPIO_AD_B0_14 (pin 94) */
  gpio_pin_config_t D6_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_14 (pin 94) */
  GPIO_PinInit(GPIO1, 14U, &D6_config);

  /* GPIO configuration of D9 on GPIO_AD_B0_15 (pin 93) */
  gpio_pin_config_t D9_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_15 (pin 93) */
  GPIO_PinInit(GPIO1, 15U, &D9_config);

  /* GPIO configuration of D15 on GPIO_AD_B1_02 (pin 90) */
  gpio_pin_config_t D15_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_02 (pin 90) */
  GPIO_PinInit(GPIO1, 18U, &D15_config);

  /* GPIO configuration of D14 on GPIO_AD_B1_03 (pin 89) */
  gpio_pin_config_t D14_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_03 (pin 89) */
  GPIO_PinInit(GPIO1, 19U, &D14_config);

  /* GPIO configuration of D7 on GPIO_AD_B1_06 (pin 84) */
  gpio_pin_config_t D7_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_06 (pin 84) */
  GPIO_PinInit(GPIO1, 22U, &D7_config);

  /* GPIO configuration of D8 on GPIO_AD_B1_07 (pin 83) */
  gpio_pin_config_t D8_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_07 (pin 83) */
  GPIO_PinInit(GPIO1, 23U, &D8_config);

  /* GPIO configuration of A0 on GPIO_AD_B1_10 (pin 80) */
  gpio_pin_config_t A0_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_10 (pin 80) */
  GPIO_PinInit(GPIO1, 26U, &A0_config);

  /* GPIO configuration of A1 on GPIO_AD_B1_11 (pin 79) */
  gpio_pin_config_t A1_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_11 (pin 79) */
  GPIO_PinInit(GPIO1, 27U, &A1_config);

  /* GPIO configuration of A2 on GPIO_AD_B1_12 (pin 78) */
  gpio_pin_config_t A2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_12 (pin 78) */
  GPIO_PinInit(GPIO1, 28U, &A2_config);

  /* GPIO configuration of A3 on GPIO_AD_B1_13 (pin 76) */
  gpio_pin_config_t A3_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_13 (pin 76) */
  GPIO_PinInit(GPIO1, 29U, &A3_config);

  /* GPIO configuration of A5 on GPIO_AD_B1_14 (pin 75) */
  gpio_pin_config_t A5_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_14 (pin 75) */
  GPIO_PinInit(GPIO1, 30U, &A5_config);

  /* GPIO configuration of A4 on GPIO_AD_B1_15 (pin 74) */
  gpio_pin_config_t A4_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_15 (pin 74) */
  GPIO_PinInit(GPIO1, 31U, &A4_config);

  /* GPIO configuration of D14_IO3 on GPIO_SD_B1_03 (pin 28) */
  gpio_pin_config_t D14_IO3_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_03 (pin 28) */
  GPIO_PinInit(GPIO3, 23U, &D14_IO3_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_05_GPIO1_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_06_GPIO1_IO06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_07_GPIO1_IO07, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_09_GPIO1_IO09, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_10_LPSPI1_SCK, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_11_LPSPI1_PCS0, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPSPI1_SDO, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPSPI1_SDI, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_14_GPIO1_IO14, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_15_GPIO1_IO15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_GPIO1_IO18, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_GPIO1_IO19, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_LPUART2_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_09_LPUART2_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_GPIO1_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_GPIO1_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_12_GPIO1_IO28, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_13_GPIO1_IO29, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_14_GPIO1_IO30, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_15_GPIO1_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_03_GPIO3_IO23, 0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_05_GPIO1_IO05, 0x10B0U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
