/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_AD_B0_07 (number 101), D3 */
/* Routed pin properties */
#define ARDUINO_D3_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_D3_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_D3_CHANNEL                                                    7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D3_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D3_GPIO_PIN                                                   7U   /*!< GPIO pin number */
#define ARDUINO_D3_GPIO_PIN_MASK                                      (1U << 7U)   /*!< GPIO pin mask */
#define ARDUINO_D3_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D3_PIN                                                        7U   /*!< PORT pin number */
#define ARDUINO_D3_PIN_MASK                                           (1U << 7U)   /*!< PORT pin mask */

/* GPIO_AD_B0_05 (number 106), D4 */
/* Routed pin properties */
#define ARDUINO_D4_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_D4_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_D4_CHANNEL                                                    5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D4_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D4_GPIO_PIN                                                   5U   /*!< GPIO pin number */
#define ARDUINO_D4_GPIO_PIN_MASK                                      (1U << 5U)   /*!< GPIO pin mask */
#define ARDUINO_D4_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D4_PIN                                                        5U   /*!< PORT pin number */
#define ARDUINO_D4_PIN_MASK                                           (1U << 5U)   /*!< PORT pin mask */

/* GPIO_AD_B0_09 (number 99), D2 */
/* Routed pin properties */
#define ARDUINO_D2_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_D2_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_D2_CHANNEL                                                    9U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D2_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D2_GPIO_PIN                                                   9U   /*!< GPIO pin number */
#define ARDUINO_D2_GPIO_PIN_MASK                                      (1U << 9U)   /*!< GPIO pin mask */
#define ARDUINO_D2_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D2_PIN                                                        9U   /*!< PORT pin number */
#define ARDUINO_D2_PIN_MASK                                           (1U << 9U)   /*!< PORT pin mask */

/* GPIO_AD_B0_06 (number 105), D5 */
/* Routed pin properties */
#define ARDUINO_D5_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_D5_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_D5_CHANNEL                                                    6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D5_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D5_GPIO_PIN                                                   6U   /*!< GPIO pin number */
#define ARDUINO_D5_GPIO_PIN_MASK                                      (1U << 6U)   /*!< GPIO pin mask */
#define ARDUINO_D5_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D5_PIN                                                        6U   /*!< PORT pin number */
#define ARDUINO_D5_PIN_MASK                                           (1U << 6U)   /*!< PORT pin mask */

/* GPIO_AD_B0_14 (number 94), D6 */
/* Routed pin properties */
#define ARDUINO_D6_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_D6_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_D6_CHANNEL                                                   14U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D6_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D6_GPIO_PIN                                                  14U   /*!< GPIO pin number */
#define ARDUINO_D6_GPIO_PIN_MASK                                     (1U << 14U)   /*!< GPIO pin mask */
#define ARDUINO_D6_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D6_PIN                                                       14U   /*!< PORT pin number */
#define ARDUINO_D6_PIN_MASK                                          (1U << 14U)   /*!< PORT pin mask */

/* GPIO_AD_B1_06 (number 84), D7 */
/* Routed pin properties */
#define ARDUINO_D7_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_D7_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_D7_CHANNEL                                                   22U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D7_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D7_GPIO_PIN                                                  22U   /*!< GPIO pin number */
#define ARDUINO_D7_GPIO_PIN_MASK                                     (1U << 22U)   /*!< GPIO pin mask */
#define ARDUINO_D7_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D7_PIN                                                       22U   /*!< PORT pin number */
#define ARDUINO_D7_PIN_MASK                                          (1U << 22U)   /*!< PORT pin mask */

/* GPIO_AD_B0_10 (number 98), CLK */
/* Routed pin properties */
#define ARDUINO_CLK_PERIPHERAL                                            LPSPI1   /*!< Peripheral name */
#define ARDUINO_CLK_SIGNAL                                                   SCK   /*!< Signal name */

/* GPIO_AD_B0_12 (number 96), MOSI */
/* Routed pin properties */
#define ARDUINO_MOSI_PERIPHERAL                                           LPSPI1   /*!< Peripheral name */
#define ARDUINO_MOSI_SIGNAL                                                  SDO   /*!< Signal name */

/* GPIO_AD_B0_11 (number 97), PCS0 */
/* Routed pin properties */
#define ARDUINO_PCS0_PERIPHERAL                                           LPSPI1   /*!< Peripheral name */
#define ARDUINO_PCS0_SIGNAL                                                 PCS0   /*!< Signal name */

/* GPIO_AD_B0_13 (number 95), MISO */
/* Routed pin properties */
#define ARDUINO_MISO_PERIPHERAL                                           LPSPI1   /*!< Peripheral name */
#define ARDUINO_MISO_SIGNAL                                                  SDI   /*!< Signal name */

/* GPIO_AD_B1_09 (number 81), UART_RX */
/* Routed pin properties */
#define ARDUINO_UART_RX_PERIPHERAL                                       LPUART2   /*!< Peripheral name */
#define ARDUINO_UART_RX_SIGNAL                                                RX   /*!< Signal name */

/* GPIO_AD_B1_08 (number 82), UART_TX */
/* Routed pin properties */
#define ARDUINO_UART_TX_PERIPHERAL                                       LPUART2   /*!< Peripheral name */
#define ARDUINO_UART_TX_SIGNAL                                                TX   /*!< Signal name */

/* GPIO_AD_B1_10 (number 80), A0 */
/* Routed pin properties */
#define ARDUINO_A0_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_A0_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_A0_CHANNEL                                                   26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_A0_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_A0_GPIO_PIN                                                  26U   /*!< GPIO pin number */
#define ARDUINO_A0_GPIO_PIN_MASK                                     (1U << 26U)   /*!< GPIO pin mask */
#define ARDUINO_A0_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_A0_PIN                                                       26U   /*!< PORT pin number */
#define ARDUINO_A0_PIN_MASK                                          (1U << 26U)   /*!< PORT pin mask */

/* GPIO_AD_B1_11 (number 79), A1 */
/* Routed pin properties */
#define ARDUINO_A1_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_A1_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_A1_CHANNEL                                                   27U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_A1_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_A1_GPIO_PIN                                                  27U   /*!< GPIO pin number */
#define ARDUINO_A1_GPIO_PIN_MASK                                     (1U << 27U)   /*!< GPIO pin mask */
#define ARDUINO_A1_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_A1_PIN                                                       27U   /*!< PORT pin number */
#define ARDUINO_A1_PIN_MASK                                          (1U << 27U)   /*!< PORT pin mask */

/* GPIO_AD_B1_12 (number 78), A2 */
/* Routed pin properties */
#define ARDUINO_A2_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_A2_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_A2_CHANNEL                                                   28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_A2_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_A2_GPIO_PIN                                                  28U   /*!< GPIO pin number */
#define ARDUINO_A2_GPIO_PIN_MASK                                     (1U << 28U)   /*!< GPIO pin mask */
#define ARDUINO_A2_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_A2_PIN                                                       28U   /*!< PORT pin number */
#define ARDUINO_A2_PIN_MASK                                          (1U << 28U)   /*!< PORT pin mask */

/* GPIO_AD_B1_13 (number 76), A3 */
/* Routed pin properties */
#define ARDUINO_A3_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_A3_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_A3_CHANNEL                                                   29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_A3_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_A3_GPIO_PIN                                                  29U   /*!< GPIO pin number */
#define ARDUINO_A3_GPIO_PIN_MASK                                     (1U << 29U)   /*!< GPIO pin mask */
#define ARDUINO_A3_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_A3_PIN                                                       29U   /*!< PORT pin number */
#define ARDUINO_A3_PIN_MASK                                          (1U << 29U)   /*!< PORT pin mask */

/* GPIO_AD_B1_15 (number 74), A4 */
/* Routed pin properties */
#define ARDUINO_A4_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_A4_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_A4_CHANNEL                                                   31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_A4_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_A4_GPIO_PIN                                                  31U   /*!< GPIO pin number */
#define ARDUINO_A4_GPIO_PIN_MASK                                     (1U << 31U)   /*!< GPIO pin mask */
#define ARDUINO_A4_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_A4_PIN                                                       31U   /*!< PORT pin number */
#define ARDUINO_A4_PIN_MASK                                          (1U << 31U)   /*!< PORT pin mask */

/* GPIO_AD_B1_14 (number 75), A5 */
/* Routed pin properties */
#define ARDUINO_A5_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_A5_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_A5_CHANNEL                                                   30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_A5_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_A5_GPIO_PIN                                                  30U   /*!< GPIO pin number */
#define ARDUINO_A5_GPIO_PIN_MASK                                     (1U << 30U)   /*!< GPIO pin mask */
#define ARDUINO_A5_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_A5_PIN                                                       30U   /*!< PORT pin number */
#define ARDUINO_A5_PIN_MASK                                          (1U << 30U)   /*!< PORT pin mask */

/* GPIO_AD_B1_07 (number 83), D8 */
/* Routed pin properties */
#define ARDUINO_D8_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_D8_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_D8_CHANNEL                                                   23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D8_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D8_GPIO_PIN                                                  23U   /*!< GPIO pin number */
#define ARDUINO_D8_GPIO_PIN_MASK                                     (1U << 23U)   /*!< GPIO pin mask */
#define ARDUINO_D8_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D8_PIN                                                       23U   /*!< PORT pin number */
#define ARDUINO_D8_PIN_MASK                                          (1U << 23U)   /*!< PORT pin mask */

/* GPIO_AD_B0_15 (number 93), D9 */
/* Routed pin properties */
#define ARDUINO_D9_PERIPHERAL                                              GPIO1   /*!< Peripheral name */
#define ARDUINO_D9_SIGNAL                                                gpio_io   /*!< Signal name */
#define ARDUINO_D9_CHANNEL                                                   15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D9_GPIO                                                    GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D9_GPIO_PIN                                                  15U   /*!< GPIO pin number */
#define ARDUINO_D9_GPIO_PIN_MASK                                     (1U << 15U)   /*!< GPIO pin mask */
#define ARDUINO_D9_PORT                                                    GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D9_PIN                                                       15U   /*!< PORT pin number */
#define ARDUINO_D9_PIN_MASK                                          (1U << 15U)   /*!< PORT pin mask */

/* GPIO_AD_B1_03 (number 89), D14 */
/* Routed pin properties */
#define ARDUINO_D14_PERIPHERAL                                             GPIO1   /*!< Peripheral name */
#define ARDUINO_D14_SIGNAL                                               gpio_io   /*!< Signal name */
#define ARDUINO_D14_CHANNEL                                                  19U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D14_GPIO                                                   GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D14_GPIO_PIN                                                 19U   /*!< GPIO pin number */
#define ARDUINO_D14_GPIO_PIN_MASK                                    (1U << 19U)   /*!< GPIO pin mask */
#define ARDUINO_D14_PORT                                                   GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D14_PIN                                                      19U   /*!< PORT pin number */
#define ARDUINO_D14_PIN_MASK                                         (1U << 19U)   /*!< PORT pin mask */

/* GPIO_AD_B1_02 (number 90), D15 */
/* Routed pin properties */
#define ARDUINO_D15_PERIPHERAL                                             GPIO1   /*!< Peripheral name */
#define ARDUINO_D15_SIGNAL                                               gpio_io   /*!< Signal name */
#define ARDUINO_D15_CHANNEL                                                  18U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D15_GPIO                                                   GPIO1   /*!< GPIO peripheral base pointer */
#define ARDUINO_D15_GPIO_PIN                                                 18U   /*!< GPIO pin number */
#define ARDUINO_D15_GPIO_PIN_MASK                                    (1U << 18U)   /*!< GPIO pin mask */
#define ARDUINO_D15_PORT                                                   GPIO1   /*!< PORT peripheral base pointer */
#define ARDUINO_D15_PIN                                                      18U   /*!< PORT pin number */
#define ARDUINO_D15_PIN_MASK                                         (1U << 18U)   /*!< PORT pin mask */

/* GPIO_SD_B1_03 (number 28), D14_IO3 */
/* Routed pin properties */
#define ARDUINO_D14_IO3_PERIPHERAL                                         GPIO3   /*!< Peripheral name */
#define ARDUINO_D14_IO3_SIGNAL                                           gpio_io   /*!< Signal name */
#define ARDUINO_D14_IO3_CHANNEL                                              23U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define ARDUINO_D14_IO3_GPIO                                               GPIO3   /*!< GPIO peripheral base pointer */
#define ARDUINO_D14_IO3_GPIO_PIN                                             23U   /*!< GPIO pin number */
#define ARDUINO_D14_IO3_GPIO_PIN_MASK                                (1U << 23U)   /*!< GPIO pin mask */
#define ARDUINO_D14_IO3_PORT                                               GPIO3   /*!< PORT peripheral base pointer */
#define ARDUINO_D14_IO3_PIN                                                  23U   /*!< PORT pin number */
#define ARDUINO_D14_IO3_PIN_MASK                                     (1U << 23U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void ARDUINO(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
